name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            binary: recuropus.exe
            artifact_name: recuropus-windows-x64.exe
          - os: ubuntu-latest
            rid: linux-x64
            binary: recuropus
            artifact_name: recuropus-linux-x64
          - os: ubuntu-22.04-arm
            rid: linux-arm64
            binary: recuropus
            artifact_name: recuropus-linux-arm64
          - os: macos-latest
            rid: osx-arm64
            binary: recuropus
            artifact_name: recuropus-mac-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: >
          dotnet publish
          -c Release
          -r ${{ matrix.rid }}
          -o ./publish
          --self-contained true
          -p:PublishSingleFile=true

      - name: Rename binary
        run: mv "publish/${{ matrix.binary }}" "publish/${{ matrix.artifact_name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: recuropus-${{ matrix.rid }}
          path: publish/${{ matrix.artifact_name }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: b${{ github.run_number }}
          name: "Build #${{ github.run_number }}"
          prerelease: true
          files: artifacts/**/*
          generate_release_notes: true
